// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGICq_RJLXPSeDLrh6KAtc0AniE-bu8HQ',
    appId: '1:370837552928:web:e34cf69daa76020a5d2145',
    messagingSenderId: '370837552928',
    projectId: 'wurkit-26a9c',
    authDomain: 'wurkit-26a9c.firebaseapp.com',
    storageBucket: 'wurkit-26a9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmV0820jX7zakHKKDwSC-BdY0KlefBgsk',
    appId: '1:370837552928:android:f9ea639f890c3c415d2145',
    messagingSenderId: '370837552928',
    projectId: 'wurkit-26a9c',
    storageBucket: 'wurkit-26a9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PoPJ6az_x6nXzx59m6EDw7p0slDBW7c',
    appId: '1:370837552928:ios:8c6ac3d5ac98a8905d2145',
    messagingSenderId: '370837552928',
    projectId: 'wurkit-26a9c',
    storageBucket: 'wurkit-26a9c.firebasestorage.app',
    iosBundleId: 'com.example.wurkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9PoPJ6az_x6nXzx59m6EDw7p0slDBW7c',
    appId: '1:370837552928:ios:8c6ac3d5ac98a8905d2145',
    messagingSenderId: '370837552928',
    projectId: 'wurkit-26a9c',
    storageBucket: 'wurkit-26a9c.firebasestorage.app',
    iosBundleId: 'com.example.wurkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGICq_RJLXPSeDLrh6KAtc0AniE-bu8HQ',
    appId: '1:370837552928:web:f963f66ed861cbfb5d2145',
    messagingSenderId: '370837552928',
    projectId: 'wurkit-26a9c',
    authDomain: 'wurkit-26a9c.firebaseapp.com',
    storageBucket: 'wurkit-26a9c.firebasestorage.app',
  );
}
